-- Create table if not exists
CREATE TABLE IF NOT EXISTS customer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL
);

-- Insert sample data
INSERT INTO customer (first_name, last_name) VALUES
    ('Ming', 'Li'),
    ('Hong', 'Wang');
